name: Run Python Script

on: 
  workflow_dispatch:

env:
  sid: ${{ secrets.SID }}
  auth: ${{ secrets.AUTH }}


jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run Python Script
        run: |
          python pip install -r requirements.txt 
          python movenet_app.py

 
